plugins:
  - jest
env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules: {
  "no-console": 0
}
